stages:
  - build

variables:
  DOCKER_IMAGE: borisdelange/linkr
  DOCKER_TAG: ${CI_COMMIT_TAG#v}
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - tags
  script:
    - echo "Building Docker image $DOCKER_IMAGE:$DOCKER_TAG"
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - echo "Docker image $DOCKER_IMAGE:$DOCKER_TAG pushed successfully"
