image: rocker/verse:latest

pages:
  script:
    - apt-get update
    - Rscript -e "install.packages(c('remotes', 'rmarkdown', 'knitr', 'htmltools'), repos = 'https://cloud.r-project.org')"
    - Rscript -e "remotes::install_gitlab('interhop/linkr/linkr', host = 'framagit.org')"
    - Rscript -e "install.packages('pkgdown')"
    - Rscript -e "pkgdown::build_site()"
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master