image: rocker/verse:latest

pages:
  script:
    - Rscript -e "install.packages('pkgdown')"
    - Rscript -e "pkgdown::build_site()"
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master