proxy:
  title: InterHop Shiny Proxy
  landing-page: /
  my-apps-mode: inline
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 3838
  authentication: simple
  admin-groups: admin
  users:
  - name: admin
    password: admin
    groups: admin
    # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: linkr
    display-name: LinkR - v0.2.0.9037
    description: A web app for visualization and analysis of healthcare data using OMOP CDM
    container-cmd: ["R", "-e", "options(shiny.port = 3838, shiny.host = '0.0.0.0'); linkr::linkr(language = 'fr', app_folder = '/root')"]
    container-image: linkr-v0.2.0.9037
    # Update container-volumes with the folder you want to share between the containers
    container-volumes: ["/home/docker-containers-files/linkr-v0.2.0.9037:/root"]
    access-groups: admin
    max-instances: 2
logging:
  file:
    shinyproxy.log
