-- ============================================================
-- Concept Set: Ionized calcium in blood (ID: 155, version 1.1.0)
-- https://example.org/data-dictionary/#/concept-sets?id=155&version=1.1.0
-- Generated by INDICATE Data Dictionary (test)
-- Date: 2026-01-01
-- ============================================================

-- ------------------------------------------------------------
-- Domain: Measurement (22 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    measurement_concept_id,
    measurement_date,
    measurement_datetime,
    CASE
        -- Reference unit: mmol/L (8753)
        WHEN unit_concept_id = 8753 THEN value_as_number
        WHEN unit_concept_id = 8840 THEN value_as_number * 0.249501 -- convert mg/dL (8840) -> mmol/L (8753)
        ELSE value_as_number -- unknown unit, no conversion available: value kept as-is (still in its original unit)
    END AS value_as_number,
    value_as_concept_id,
    CASE
        WHEN unit_concept_id IN (8753, 8840) THEN 8753 -- normalized to reference unit mmol/L (8753)
        ELSE unit_concept_id -- no conversion for this (concept, unit): kept as-is, value stays in its original unit
    END AS unit_concept_id,
    measurement_source_value,
    measurement_source_concept_id,
    unit_source_value
FROM measurement
WHERE measurement_concept_id IN (
    3013784 -- Calcium.ionized [Moles/volume] in Serum or Plasma by Ion-selective membrane electrode (ISE)
   ,3015774 -- Calcium.ionized [Moles/volume] in Serum or Plasma by calculation
   ,3016431 -- Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Serum or Plasma
   ,3021119 -- Calcium.ionized [Moles/volume] in Blood
   ,3021347 -- Calcium.ionized [Moles/volume] in Serum or Plasma
   ,3024250 -- Calcium.ionized [Mass/volume] in Serum or Plasma by Ion-selective membrane electrode (ISE)
   ,3027694 -- Calcium.ionized [Mass/volume] in Serum or Plasma
   ,3032271 -- Calcium.ionized [Moles/volume] in Mixed venous blood
   ,3033705 -- Calcium.ionized [Moles/volume] in Venous blood
   ,3035279 -- Calcium.ionized [Moles/volume] in Capillary blood
   ,3036426 -- Calcium.ionized [Mass/volume] in Blood
   ,3039602 -- Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Capillary blood
   ,3041671 -- Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Venous blood
   ,3041706 -- Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Arterial blood
   ,3044331 -- Calcium.ionized [Moles/volume] in Arterial blood
   ,3048816 -- Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Blood
   ,3050068 -- Calcium.ionized [Moles/volume] in Blood by Ion-selective membrane electrode (ISE)
   ,40760451 -- Calcium.ionized [Mass/volume] adjusted to pH 7.4 in Serum or Plasma by Ion-selective membrane electrode (ISE)
   ,40762532 -- Calcium.ionized [Mass/volume] in Arterial blood
   ,40762533 -- Calcium.ionized [Mass/volume] in Venous blood
   ,40762534 -- Calcium.ionized [Mass/volume] adjusted to pH 7.4 in Arterial blood by Ion-selective membrane electrode (ISE)
   ,40762535 -- Calcium.ionized [Mass/volume] adjusted to pH 7.4 in Venous blood by Ion-selective membrane electrode (ISE)
)
-- Optional: uncomment to drop rows whose unit cannot be converted to the reference unit
-- AND unit_concept_id IN (8753, 8840)
;