-- ============================================================
-- Concept Set: Glycated hemoglobin (HbA1c) in blood (ID: 184, version 1.1.1)
-- https://example.org/data-dictionary/#/concept-sets?id=184&version=1.1.1
-- Generated by INDICATE Data Dictionary (test)
-- Date: 2026-01-01
-- ============================================================

-- ------------------------------------------------------------
-- Domain: Measurement (8 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    measurement_concept_id,
    measurement_date,
    measurement_datetime,
    CASE
        -- Reference unit: % (8554)
        WHEN unit_concept_id = 8554 THEN value_as_number
        WHEN unit_concept_id = 9579 THEN value_as_number * 0.09148 + 2.152 -- convert mmol/mol (9579) -> % (8554)
        ELSE value_as_number -- unknown unit, no conversion available: value kept as-is (still in its original unit)
    END AS value_as_number,
    value_as_concept_id,
    CASE
        WHEN unit_concept_id IN (8554, 9579) THEN 8554 -- normalized to reference unit % (8554)
        ELSE unit_concept_id -- no conversion for this (concept, unit): kept as-is, value stays in its original unit
    END AS unit_concept_id,
    measurement_source_value,
    measurement_source_concept_id,
    unit_source_value
FROM measurement
WHERE measurement_concept_id IN (
    3003309 -- Hemoglobin A1c/Hemoglobin.total in Blood by Electrophoresis
   ,3004410 -- Hemoglobin A1c/Hemoglobin.total in Blood
   ,3005673 -- Hemoglobin A1c/Hemoglobin.total in Blood by HPLC
   ,3007263 -- Hemoglobin A1c/Hemoglobin.total in Blood by calculation
   ,3034639 -- Hemoglobin A1c [Mass/volume] in Blood
   ,40762352 -- Hemoglobin A1c/Hemoglobin.total in Blood by IFCC protocol
   ,40765129 -- Hemoglobin A1c/Hemoglobin.total in Blood by JDS/JSCC protocol
   ,42869630 -- Hemoglobin A1c/Hemoglobin.total [Pure mass fraction] in Blood
)
-- Optional: uncomment to drop rows whose unit cannot be converted to the reference unit
-- AND unit_concept_id IN (8554, 9579)
;