-- ============================================================
-- Concept Set: Endotracheal intubation (ID: 305, version 1.1.0)
-- https://example.org/data-dictionary/#/concept-sets?id=305&version=1.1.0
-- Generated by INDICATE Data Dictionary (test)
-- Date: 2026-01-01
-- ============================================================

-- ------------------------------------------------------------
-- Domain: Meas Value (1 concepts)
-- ------------------------------------------------------------
-- No OMOP CDM table mapping for domain "Meas Value".
-- Concepts:
--   36309319 -- Unplanned intubation

-- ------------------------------------------------------------
-- Domain: Observation (1 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    observation_concept_id,
    observation_date,
    observation_datetime,
    value_as_number,
    value_as_string,
    value_as_concept_id,
    unit_concept_id,
    observation_source_value,
    observation_source_concept_id
FROM observation
WHERE observation_concept_id IN (
    36660691 -- Difficult intubation
)
;
-- ------------------------------------------------------------
-- Domain: Procedure (21 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    procedure_concept_id,
    procedure_date,
    procedure_datetime,
    procedure_type_concept_id,
    procedure_source_value,
    procedure_source_concept_id
FROM procedure_occurrence
WHERE procedure_concept_id IN (
    4013354 -- Insertion of endotracheal tube
   ,4056812 -- Laryngeal intubation for inhalation
   ,4058031 -- Endotracheal intubation, emergency procedure
   ,4082243 -- Emergency laryngeal intubation
   ,4119642 -- Awake intubation
   ,4140765 -- Digital assisted intubation
   ,4179373 -- Insertion of endotracheal tube using laryngoscope
   ,4283807 -- Intubation of larynx
   ,4287921 -- Retrograde intubation
   ,4303945 -- Tracheal intubation through a laryngeal mask airway
   ,4335481 -- Orotracheal intubation
   ,4335583 -- Tracheal intubation using rigid bronchoscope
   ,4335584 -- Nasal intubation awake
   ,4335585 -- Endobronchial intubation
   ,4337045 -- Blind nasal intubation
   ,4337615 -- Orotracheal fiberoptic intubation
   ,4337616 -- Nasotracheal intubation
   ,4337617 -- Nasotracheal fiberoptic intubation
   ,4339623 -- Oral intubation awake
   ,37116698 -- Insertion of double lumen tracheobronchial tube
   ,40487536 -- Intubation of respiratory tract
)
;