-- ============================================================
-- Concept Set: Positive End-Expiratory Pressure (PEEP) (ID: 318, version 1.1.2)
-- https://example.org/data-dictionary/#/concept-sets?id=318&version=1.1.2
-- Generated by INDICATE Data Dictionary (test)
-- Date: 2026-01-01
-- ============================================================

-- ------------------------------------------------------------
-- Domain: Measurement (4 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    measurement_concept_id,
    measurement_date,
    measurement_datetime,
    CASE
        -- Reference unit: mbar (720858)
        WHEN unit_concept_id = 720858 THEN value_as_number
        WHEN unit_concept_id = 44777590 THEN value_as_number * 0.980665 -- convert cm[H2O] (44777590) -> mbar (720858)
        ELSE value_as_number -- unknown unit, no conversion available: value kept as-is (still in its original unit)
    END AS value_as_number,
    value_as_concept_id,
    CASE
        WHEN unit_concept_id IN (720858, 44777590) THEN 720858 -- normalized to reference unit mbar (720858)
        ELSE unit_concept_id -- no conversion for this (concept, unit): kept as-is, value stays in its original unit
    END AS unit_concept_id,
    measurement_source_value,
    measurement_source_concept_id,
    unit_source_value
FROM measurement
WHERE measurement_concept_id IN (
    3022875 -- Positive end expiratory pressure setting Ventilator
   ,3035822 -- Intrinsic PEEP Respiratory system
   ,42527140 -- Total PEEP Respiratory system
   ,42528515 -- Extrinsic PEEP Respiratory system
)
-- Optional: uncomment to drop rows whose unit cannot be converted to the reference unit
-- AND unit_concept_id IN (720858, 44777590)
;
-- ------------------------------------------------------------
-- Domain: Observation (3 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    observation_concept_id,
    observation_date,
    observation_datetime,
    value_as_number,
    value_as_string,
    value_as_concept_id,
    unit_concept_id,
    observation_source_value,
    observation_source_concept_id
FROM observation
WHERE observation_concept_id IN (
    4160171 -- Best positive end expiratory pressure
   ,4216746 -- Positive end expiratory pressure setting
   ,4353713 -- Positive end expiratory pressure
)
;