-- ============================================================
-- Concept Set: Body temperature (ID: 330, version 1.2.0)
-- https://example.org/data-dictionary/#/concept-sets?id=330&version=1.2.0
-- Generated by INDICATE Data Dictionary (test)
-- Date: 2026-01-01
-- ============================================================

-- ------------------------------------------------------------
-- Domain: Measurement (33 concepts)
-- ------------------------------------------------------------

SELECT
    person_id,
    measurement_concept_id,
    measurement_date,
    measurement_datetime,
    CASE
        -- Reference unit: Cel (586323)
        WHEN unit_concept_id = 586323 THEN value_as_number
        WHEN unit_concept_id = 9289 THEN value_as_number * 0.555556 - 17.777778 -- convert [degF] (9289) -> Cel (586323)
        ELSE value_as_number -- unknown unit, no conversion available: value kept as-is (still in its original unit)
    END AS value_as_number,
    value_as_concept_id,
    CASE
        WHEN unit_concept_id IN (586323, 9289) THEN 586323 -- normalized to reference unit Cel (586323)
        ELSE unit_concept_id -- no conversion for this (concept, unit): kept as-is, value stays in its original unit
    END AS unit_concept_id,
    measurement_source_value,
    measurement_source_concept_id,
    unit_source_value
FROM measurement
WHERE measurement_concept_id IN (
    1259509 -- Body temperature - Groin
   ,3006322 -- Oral temperature
   ,3007416 -- Body temperature - Intravascular
   ,3020891 -- Body temperature
   ,3022060 -- Rectal temperature
   ,3025085 -- Axillary temperature
   ,3025704 -- Body temperature - Urinary bladder
   ,3025926 -- Body temperature - Core
   ,3032679 -- Body temperature --after transfusion reaction
   ,4143731 -- Rectal temperature
   ,4174894 -- Core body temperature
   ,4188706 -- Axillary temperature
   ,4189949 -- Groin temperature
   ,4212763 -- Forehead temperature
   ,4215364 -- Tympanic temperature
   ,4218834 -- Oral temperature
   ,4239770 -- Temperature of pinna
   ,4302666 -- Body temperature
   ,4329518 -- Body temperature taken with digital thermometer
   ,4333349 -- Temperature of esophagus
   ,21490586 -- Blood temperature
   ,21490587 -- Arterial blood temperature
   ,21490588 -- Esophageal temperature
   ,21490590 -- Nasopharyngeal temperature
   ,21490769 -- Venous blood temperature
   ,21490870 -- Bladder temperature via Foley
   ,21490906 -- Nasal temperature
   ,21490907 -- Ear temperature
   ,37019573 -- Body temperature - Brain
   ,37164002 -- Core body temperature measured in blood
   ,44782834 -- Nasopharyngeal temperature
   ,44782835 -- Core body temperature measured at urinary bladder
   ,46235152 -- Body temperature - Temporal artery
)
-- Optional: uncomment to drop rows whose unit cannot be converted to the reference unit
-- AND unit_concept_id IN (586323, 9289)
;