-- ============================================================
-- Concept Set: Glasgow coma scale total (ID: 8, version 1.1.0)
-- https://example.org/data-dictionary/#/concept-sets?id=8&version=1.1.0
-- Generated by INDICATE Data Dictionary (test)
-- Date: 2026-01-01
-- ============================================================

-- ------------------------------------------------------------
-- Domain: Measurement (1 concepts)
-- ------------------------------------------------------------
-- Note: no reference unit selected — raw value_as_number returned without conversion.

SELECT
    person_id,
    measurement_concept_id,
    measurement_date,
    measurement_datetime,
    value_as_number,
    value_as_concept_id,
    unit_concept_id,
    measurement_source_value,
    measurement_source_concept_id,
    unit_source_value
FROM measurement
WHERE measurement_concept_id IN (
    3007194 -- Glasgow coma score total
)
;