"""add wiki_pages table

Revision ID: 077c64f58273
Revises: 0a16400792d6
Create Date: 2026-07-05 23:09:49.616476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '077c64f58273'
down_revision: Union[str, None] = '0a16400792d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.String(length=40), nullable=True),
    sa.Column('review_due_at', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_wiki_pages_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_pages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki_pages')
    # ### end Alembic commands ###
