"""mapping projects concept mappings service mappings

Revision ID: 0b0cca1331dc
Revises: d837af51f909
Create Date: 2026-07-08 14:02:21.230555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0b0cca1331dc'
down_revision: Union[str, None] = 'd837af51f909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('vocabulary_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('file_source_data', sa.JSON(), nullable=True),
    sa.Column('raw_file_sha', sa.String(length=64), nullable=True),
    sa.Column('raw_file_name', sa.String(length=255), nullable=True),
    sa.Column('concept_set_ids', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('import_batches', sa.JSON(), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mapping_projects_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_projects'))
    )
    op.create_table('service_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_service_mappings_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_mappings'))
    )
    op.create_table('concept_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_concept_id', sa.BigInteger(), nullable=True),
    sa.Column('source_concept_name', sa.Text(), nullable=True),
    sa.Column('source_vocabulary_id', sa.String(length=255), nullable=True),
    sa.Column('source_domain_id', sa.String(length=255), nullable=True),
    sa.Column('source_concept_code', sa.String(length=255), nullable=True),
    sa.Column('source_frequency', sa.Integer(), nullable=True),
    sa.Column('source_category_id', sa.String(length=255), nullable=True),
    sa.Column('source_subcategory_id', sa.String(length=255), nullable=True),
    sa.Column('source_concept_class_id', sa.String(length=255), nullable=True),
    sa.Column('target_concept_id', sa.BigInteger(), nullable=True),
    sa.Column('target_concept_name', sa.Text(), nullable=True),
    sa.Column('target_vocabulary_id', sa.String(length=255), nullable=True),
    sa.Column('target_domain_id', sa.String(length=255), nullable=True),
    sa.Column('target_concept_code', sa.String(length=255), nullable=True),
    sa.Column('target_concept_class_id', sa.String(length=255), nullable=True),
    sa.Column('target_standard_concept', sa.String(length=10), nullable=True),
    sa.Column('concept_set_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_type', sa.String(length=50), nullable=True),
    sa.Column('equivalence', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('mapped_by', sa.Text(), nullable=True),
    sa.Column('mapped_by_details', sa.JSON(), nullable=True),
    sa.Column('mapped_on', sa.String(length=40), nullable=True),
    sa.Column('assigned_reviewer', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_by_details', sa.JSON(), nullable=True),
    sa.Column('reviewed_on', sa.String(length=40), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mapping_projects.id'], name=op.f('fk_concept_mappings_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_mappings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_mappings')
    op.drop_table('service_mappings')
    op.drop_table('mapping_projects')
    # ### end Alembic commands ###
