"""merge notifications and assistant removal

Revision ID: 34f8f2a646cb
Revises: 0d1f42d46e99, ffcd32546ab7
Create Date: 2026-09-23 21:39:02.030844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '34f8f2a646cb'
down_revision: Union[str, None] = ('0d1f42d46e99', 'ffcd32546ab7')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
