"""mapping_projects: scores_file_sha/name columns

Revision ID: 42d9cc772afb
Revises: 7e0314d3066c
Create Date: 2026-07-11 13:32:31.190396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '42d9cc772afb'
down_revision: Union[str, None] = '7e0314d3066c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores_file_sha', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('scores_file_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_projects', schema=None) as batch_op:
        batch_op.drop_column('scores_file_name')
        batch_op.drop_column('scores_file_sha')

    # ### end Alembic commands ###
