"""concept stats cache

Revision ID: 4866b8aab3b1
Revises: 93ddcea820ca
Create Date: 2026-07-09 08:03:45.296138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '4866b8aab3b1'
down_revision: Union[str, None] = '93ddcea820ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # An earlier iteration of this revision created concept_count_caches (a JSON
    # count cache); it was superseded by a server-side Parquet cache, so drop it
    # if a database was upgraded through that version.
    op.execute("DROP TABLE IF EXISTS concept_count_caches")
    op.create_table(
        'concept_stats_caches',
        sa.Column('data_source_id', sa.String(length=36), nullable=False),
        sa.Column('concept_id', sa.Integer(), nullable=False),
        sa.Column('stats', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_concept_stats_caches_data_source_id'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('data_source_id', 'concept_id', name=op.f('pk_concept_stats_caches')),
    )


def downgrade() -> None:
    op.drop_table('concept_stats_caches')
