"""workspace default_env_packages

Revision ID: 4cc5117ea11e
Revises: e329b4a06077
Create Date: 2026-07-31 22:12:53.547284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4cc5117ea11e'
down_revision: Union[str, None] = 'e329b4a06077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_env_packages', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('default_env_packages')

    # ### end Alembic commands ###
