"""readme attachments workspace scope

Revision ID: 597b5f4a5dc7
Revises: c5f24c0732da
Create Date: 2026-07-10 13:57:04.832832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '597b5f4a5dc7'
down_revision: Union[str, None] = 'c5f24c0732da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readme_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('project_uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_readme_attachments_workspace_id'), 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readme_attachments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_readme_attachments_workspace_id'), type_='foreignkey')
        batch_op.alter_column('project_uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('workspace_id')

    # ### end Alembic commands ###
