"""initial schema

Revision ID: 669558a7416a
Revises: 
Create Date: 2026-07-13 16:39:07.480122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '669558a7416a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('synced_oid', sa.String(length=40), nullable=False),
    sa.Column('checked_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_sync_state')),
    sa.UniqueConstraint('scope', 'entity_id', 'branch', name='uq_git_sync_state_key')
    )
    op.create_table('organizations',
    sa.Column('name', app.models.base.LocalizedText(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('location', app.models.base.LocalizedText(), nullable=True),
    sa.Column('country', app.models.base.LocalizedText(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('custom_type', app.models.base.LocalizedText(), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.JSON(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('stats_cache',
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stats_cache')),
    sa.UniqueConstraint('scope', 'cache_key', name='uq_stats_cache_scope_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('entity_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('visited_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entity_visits_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_visits')),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_entity_visits_user_entity')
    )
    with op.batch_alter_table('entity_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_visits_user_id'), ['user_id'], unique=False)

    op.create_table('execution_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_execution_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_sessions'))
    )
    with op.batch_alter_table('execution_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_sessions_project_uid'), ['project_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('plugin_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_plugins_owner_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugins')),
    sa.UniqueConstraint('uid', name=op.f('uq_plugins_uid'))
    )
    op.create_table('workspaces',
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('readme', sa.JSON(), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_workspaces_created_by_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('concept_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=False),
    sa.Column('resolved_concept_ids', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('unique_id', sa.String(length=255), nullable=True),
    sa.Column('source_repo', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_concept_sets_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_sets'))
    )
    op.create_table('data_catalogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('anonymization', sa.JSON(), nullable=False),
    sa.Column('category_column', sa.String(length=255), nullable=True),
    sa.Column('subcategory_column', sa.String(length=255), nullable=True),
    sa.Column('period_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_computed_at', sa.String(length=40), nullable=True),
    sa.Column('last_compute_duration_ms', sa.Integer(), nullable=True),
    sa.Column('dcat_ap_metadata', sa.JSON(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('organization', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_data_catalogs_created_by_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_data_catalogs_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_catalogs'))
    )
    op.create_table('data_sources',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('connection_secret', sa.Text(), nullable=True),
    sa.Column('schema_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_vocabulary_reference', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_data_sources_created_by_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_data_sources_owner_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_data_sources_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_table('dq_rule_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', sa.String(length=40), nullable=True),
    sa.Column('last_run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('organization', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dq_rule_sets_created_by_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dq_rule_sets_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dq_rule_sets'))
    )
    op.create_table('etl_pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('source_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('target_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_project_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', sa.String(length=40), nullable=True),
    sa.Column('last_run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('organization', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_etl_pipelines_created_by_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_etl_pipelines_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_pipelines'))
    )
    op.create_table('mapping_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('vocabulary_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('file_source_data', sa.JSON(), nullable=True),
    sa.Column('raw_file_sha', sa.String(length=64), nullable=True),
    sa.Column('raw_file_name', sa.String(length=255), nullable=True),
    sa.Column('scores_file_sha', sa.String(length=64), nullable=True),
    sa.Column('scores_file_name', sa.String(length=255), nullable=True),
    sa.Column('concept_set_ids', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('import_batches', sa.JSON(), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('organization', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_mapping_projects_created_by_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mapping_projects_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_projects'))
    )
    op.create_table('projects',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('short_description', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('todos', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('readme', sa.JSON(), nullable=True),
    sa.Column('linked_data_source_ids', sa.JSON(), nullable=True),
    sa.Column('organization', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('catalog_visibility', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_projects'))
    )
    op.create_table('schema_presets',
    sa.Column('preset_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_schema_presets_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preset_id', name=op.f('pk_schema_presets'))
    )
    op.create_table('service_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_service_mappings_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_mappings'))
    )
    op.create_table('source_concept_id_entries',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('badge_label', sa.String(length=255), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=255), nullable=False),
    sa.Column('concept_code', sa.String(length=255), nullable=False),
    sa.Column('source_concept_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_concept_id_entries_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_concept_id_entries'))
    )
    op.create_table('source_concept_id_ranges',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('badge_label', sa.String(length=255), nullable=False),
    sa.Column('range_start', sa.BigInteger(), nullable=False),
    sa.Column('range_end', sa.BigInteger(), nullable=False),
    sa.Column('next_id', sa.BigInteger(), nullable=False),
    sa.Column('total_concepts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_concept_id_ranges_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'badge_label', name=op.f('pk_source_concept_id_ranges'))
    )
    op.create_table('sql_script_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('default_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('organization', sa.JSON(), nullable=True),
    sa.Column('lineage_id', sa.String(length=36), nullable=True),
    sa.Column('parent_lineage_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sql_script_collections_created_by_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sql_script_collections_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sql_script_collections'))
    )
    op.create_table('user_plugins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('git_remote_secret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_user_plugins_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_plugins'))
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.String(length=40), nullable=True),
    sa.Column('review_due_at', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_wiki_pages_created_by_id')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_wiki_pages_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_pages'))
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_members'))
    )
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('criteria_tree', sa.JSON(), nullable=False),
    sa.Column('custom_sql', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('attrition', sa.JSON(), nullable=True),
    sa.Column('materialization', sa.JSON(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_cohorts_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts'))
    )
    op.create_table('concept_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_concept_id', sa.BigInteger(), nullable=True),
    sa.Column('source_concept_name', sa.Text(), nullable=True),
    sa.Column('source_vocabulary_id', sa.String(length=255), nullable=True),
    sa.Column('source_domain_id', sa.String(length=255), nullable=True),
    sa.Column('source_concept_code', sa.String(length=255), nullable=True),
    sa.Column('source_frequency', sa.Integer(), nullable=True),
    sa.Column('source_category_id', sa.String(length=255), nullable=True),
    sa.Column('source_subcategory_id', sa.String(length=255), nullable=True),
    sa.Column('source_concept_class_id', sa.String(length=255), nullable=True),
    sa.Column('target_concept_id', sa.BigInteger(), nullable=True),
    sa.Column('target_concept_name', sa.Text(), nullable=True),
    sa.Column('target_vocabulary_id', sa.String(length=255), nullable=True),
    sa.Column('target_domain_id', sa.String(length=255), nullable=True),
    sa.Column('target_concept_code', sa.String(length=255), nullable=True),
    sa.Column('target_concept_class_id', sa.String(length=255), nullable=True),
    sa.Column('target_standard_concept', sa.String(length=10), nullable=True),
    sa.Column('concept_set_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_type', sa.String(length=50), nullable=True),
    sa.Column('equivalence', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('mapped_by', sa.Text(), nullable=True),
    sa.Column('mapped_by_details', sa.JSON(), nullable=True),
    sa.Column('mapped_on', sa.String(length=40), nullable=True),
    sa.Column('assigned_reviewer', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_by_details', sa.JSON(), nullable=True),
    sa.Column('reviewed_on', sa.String(length=40), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mapping_projects.id'], name=op.f('fk_concept_mappings_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_mappings'))
    )
    op.create_table('concept_stats_caches',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_concept_stats_caches_data_source_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_source_id', 'concept_id', name=op.f('pk_concept_stats_caches'))
    )
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('filter_config', sa.JSON(), nullable=False),
    sa.Column('show_widget_titles', sa.Boolean(), nullable=True),
    sa.Column('default_dataset_file_id', sa.String(length=36), nullable=True),
    sa.Column('widget_spacing', sa.Integer(), nullable=True),
    sa.Column('reload_widgets_on_tab_switch', sa.Boolean(), nullable=True),
    sa.Column('fit_to_height', sa.Boolean(), nullable=True),
    sa.Column('grid_v', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dashboards_created_by_id')),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_dashboards_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboards'))
    )
    op.create_table('data_source_files',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_data_source_files_data_source_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_files'))
    )
    op.create_table('dataset_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('dataset_path', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_dataset_analyses_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_analyses'))
    )
    op.create_table('dataset_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('parse_options', sa.JSON(), nullable=True),
    sa.Column('data_sha', sa.String(length=64), nullable=True),
    sa.Column('raw_sha', sa.String(length=64), nullable=True),
    sa.Column('raw_file_name', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dataset_files_created_by_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_dataset_files_owner_id')),
    sa.ForeignKeyConstraint(['parent_id'], ['dataset_files.id'], name=op.f('fk_dataset_files_parent_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_dataset_files_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_files'))
    )
    op.create_table('dq_custom_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_set_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['dq_rule_sets.id'], name=op.f('fk_dq_custom_checks_rule_set_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dq_custom_checks'))
    )
    op.create_table('etl_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['etl_pipelines.id'], name=op.f('fk_etl_files_pipeline_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_files'))
    )
    op.create_table('ide_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('connection_secret', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_ide_connections_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ide_connections'))
    )
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_pipelines_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines'))
    )
    op.create_table('project_members',
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_project_members_project_uid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_uid', 'user_id', name=op.f('pk_project_members'))
    )
    op.create_table('readme_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('blob_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_readme_attachments_project_uid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_readme_attachments_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readme_attachments'))
    )
    op.create_table('sql_script_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['sql_script_collections.id'], name=op.f('fk_sql_script_files_collection_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sql_script_files'))
    )
    op.create_table('wiki_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('blob_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_attachments_page_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_wiki_attachments_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_attachments'))
    )
    op.create_table('dashboard_tabs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('parent_tab_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_tabs_dashboard_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_tabs'))
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tab_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_file_id', sa.String(length=36), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['dashboard_tabs.id'], name=op.f('fk_dashboard_widgets_tab_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_widgets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_widgets')
    op.drop_table('dashboard_tabs')
    op.drop_table('wiki_attachments')
    op.drop_table('sql_script_files')
    op.drop_table('readme_attachments')
    op.drop_table('project_members')
    op.drop_table('pipelines')
    op.drop_table('ide_connections')
    op.drop_table('etl_files')
    op.drop_table('dq_custom_checks')
    op.drop_table('dataset_files')
    op.drop_table('dataset_analyses')
    op.drop_table('data_source_files')
    op.drop_table('dashboards')
    op.drop_table('concept_stats_caches')
    op.drop_table('concept_mappings')
    op.drop_table('cohorts')
    op.drop_table('workspace_members')
    op.drop_table('wiki_pages')
    op.drop_table('user_plugins')
    op.drop_table('sql_script_collections')
    op.drop_table('source_concept_id_ranges')
    op.drop_table('source_concept_id_entries')
    op.drop_table('service_mappings')
    op.drop_table('schema_presets')
    op.drop_table('projects')
    op.drop_table('mapping_projects')
    op.drop_table('etl_pipelines')
    op.drop_table('dq_rule_sets')
    op.drop_table('data_sources')
    op.drop_table('data_catalogs')
    op.drop_table('concept_sets')
    op.drop_table('workspaces')
    op.drop_table('plugins')
    with op.batch_alter_table('execution_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_execution_sessions_project_uid'))

    op.drop_table('execution_sessions')
    with op.batch_alter_table('entity_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_visits_user_id'))

    op.drop_table('entity_visits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_external_id'))

    op.drop_table('users')
    op.drop_table('stats_cache')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('git_sync_state')
    # ### end Alembic commands ###
