"""stats_cache table (shared database/catalog result cache)

Revision ID: 75244d51e062
Revises: 4d744166dce4
Create Date: 2026-07-11 15:43:07.005895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '75244d51e062'
down_revision: Union[str, None] = '4d744166dce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_cache',
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stats_cache')),
    sa.UniqueConstraint('scope', 'cache_key', name='uq_stats_cache_scope_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_cache')
    # ### end Alembic commands ###
