"""drop wiki_pages history column

Revision ID: 7e0314d3066c
Revises: 597b5f4a5dc7
Create Date: 2026-07-10 15:13:01.233906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '7e0314d3066c'
down_revision: Union[str, None] = '597b5f4a5dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.drop_column('history')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###
