"""etl_pipelines and etl_files

Revision ID: 808b1ba5efe8
Revises: 3d30e3d02012
Create Date: 2026-07-08 12:16:04.434872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '808b1ba5efe8'
down_revision: Union[str, None] = '3d30e3d02012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('source_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('target_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_project_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', sa.String(length=40), nullable=True),
    sa.Column('last_run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_etl_pipelines_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_pipelines'))
    )
    op.create_table('etl_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['etl_pipelines.id'], name=op.f('fk_etl_files_pipeline_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_files')
    op.drop_table('etl_pipelines')
    # ### end Alembic commands ###
