"""dashboards persistence

Revision ID: 904d4117f8ab
Revises: b29f73555fd4
Create Date: 2026-07-10 08:30:49.208141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '904d4117f8ab'
down_revision: Union[str, None] = 'b29f73555fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('filter_config', sa.JSON(), nullable=False),
    sa.Column('show_widget_titles', sa.Boolean(), nullable=True),
    sa.Column('default_dataset_file_id', sa.String(length=36), nullable=True),
    sa.Column('widget_spacing', sa.Integer(), nullable=True),
    sa.Column('reload_widgets_on_tab_switch', sa.Boolean(), nullable=True),
    sa.Column('fit_to_height', sa.Boolean(), nullable=True),
    sa.Column('grid_v', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_dashboards_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboards'))
    )
    op.create_table('dashboard_tabs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('parent_tab_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_tabs_dashboard_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_tabs'))
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tab_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_file_id', sa.String(length=36), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['dashboard_tabs.id'], name=op.f('fk_dashboard_widgets_tab_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_widgets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_widgets')
    op.drop_table('dashboard_tabs')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
