"""badge categories declared by a workspace

Scoped labels, GitLab-style: a workspace declares categories (name, colour,
exclusive) and its entities' badges carry them as a `Category::value` label.
Stored on the workspace rather than as a table of their own — a category has no
page, no URL and no lifecycle, and workspace.json already carries the record.

Revision ID: a1b2c3d4e5f7
Revises: 392c0e7ae5b8
Create Date: 2026-08-23 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f7'
down_revision: Union[str, None] = '392c0e7ae5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_categories', sa.JSON(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('badge_categories')
