"""databases become publishable entities: docs, licence, version, git link

A database is the last top-level entity with no README, no licence, no stable
export id and no git link. It gets them so an open dataset (synthetic data, the
MIMIC-IV demo) can be shared through the catalog like any other entity.

What is shared is documentation and metadata only: the export reduces
connection_config to `engine` (see sanitizeConnectionConfig / the allowlist in
workspace_export.py) and writes no rows. Adding actual data to such a repo is
done by hand, outside the app, so the app can never be the path by which
patient data leaks.

`badges` and `version` already existed client-side — the UI collected them and
the server silently dropped them, having no column to write them to.

Revision ID: b2c3d4e5f8a1
Revises: a1b2c3d4e5f7
Create Date: 2026-08-23 22:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f8a1'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('badges', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('readme', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('license', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('git_remote_config', sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column('version', sa.String(length=20), nullable=False, server_default='0.1.0')
        )
        batch_op.add_column(sa.Column('organization', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('lineage_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('parent_lineage_id', sa.String(length=36), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('parent_lineage_id')
        batch_op.drop_column('lineage_id')
        batch_op.drop_column('organization')
        batch_op.drop_column('version')
        batch_op.drop_column('git_remote_config')
        batch_op.drop_column('license')
        batch_op.drop_column('readme')
        batch_op.drop_column('badges')
        batch_op.drop_column('entity_id')
