"""user_plugins workspace_id not null

Revision ID: b8112073e099
Revises: 7cb062086959
Create Date: 2026-07-10 08:04:09.868427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b8112073e099'
down_revision: Union[str, None] = '7cb062086959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Plugins are now strictly workspace-scoped. Drop any legacy "global" plugin
    # (workspace_id IS NULL) — there is no home for them under the new model —
    # then make the column NOT NULL. batch_alter_table so SQLite can rebuild it.
    op.execute(sa.text("DELETE FROM user_plugins WHERE workspace_id IS NULL"))
    with op.batch_alter_table("user_plugins") as batch:
        batch.alter_column("workspace_id", existing_type=sa.String(length=36), nullable=False)


def downgrade() -> None:
    with op.batch_alter_table("user_plugins") as batch:
        batch.alter_column("workspace_id", existing_type=sa.String(length=36), nullable=True)
