"""readme + wiki attachments

Revision ID: be73afd43dcd
Revises: 904d4117f8ab
Create Date: 2026-07-10 12:46:26.292096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'be73afd43dcd'
down_revision: Union[str, None] = '904d4117f8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readme_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('blob_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_readme_attachments_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readme_attachments'))
    )
    op.create_table('wiki_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('blob_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_attachments_page_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_wiki_attachments_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_attachments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki_attachments')
    op.drop_table('readme_attachments')
    # ### end Alembic commands ###
