"""execution sessions

Revision ID: c0cdf1bbef81
Revises: e883fbf236cf
Create Date: 2026-07-09 12:47:38.633647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'c0cdf1bbef81'
down_revision: Union[str, None] = 'e883fbf236cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_execution_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_sessions'))
    )
    with op.batch_alter_table('execution_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_sessions_project_uid'), ['project_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_execution_sessions_project_uid'))

    op.drop_table('execution_sessions')
    # ### end Alembic commands ###
