"""execution_sessions.language (language-scoped sessions)

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-08-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills pre-existing sessions as Python (they had no
    # language); they'll simply show under Python scripts.
    with op.batch_alter_table('execution_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'language',
                sa.String(length=16),
                nullable=False,
                server_default='python',
            )
        )
        batch_op.create_index(
            'ix_execution_sessions_language', ['language'], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table('execution_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_sessions_language')
        batch_op.drop_column('language')
