"""a database's name and description become multilingual

Every other top-level entity already carries a LocalizedString name; a database
was the exception, which meant a database published to the catalog could not be
named in the reader's language.

The columns become LocalizedText — a JSON column that reads a legacy bare string
back unchanged — and the existing rows are converted to {"<lang>": value}. The
tolerant read is the safety net (a row this backfill misses still decodes); the
backfill is what makes the data uniform for code that iterates the map.

`description`'s server_default of '' has to go with it: an empty string is not a
valid LocalizedString, and it reads back as None.

Revision ID: c3d4e5f8a1b2
Revises: b2c3d4e5f8a1
Create Date: 2026-08-23 22:55:00.000000

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f8a1b2'
down_revision: Union[str, None] = 'b2c3d4e5f8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: Language every pre-existing name is filed under. These rows were written
#: before databases were multilingual, so their real language is unknown; 'en'
#: is what localized() falls back to, so the name keeps rendering either way.
_LEGACY_LANG = "en"


def _is_json_object(raw: str) -> bool:
    try:
        return isinstance(json.loads(raw), dict)
    except (ValueError, TypeError):
        return False


def upgrade() -> None:
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.alter_column('name', existing_type=sa.String(length=255), type_=sa.Text())
        # NOT NULL and the '' default both have to go: an empty string is not a
        # valid LocalizedString, so "no description" is now NULL.
        batch_op.alter_column(
            'description',
            existing_type=sa.Text(),
            type_=sa.Text(),
            server_default=None,
            nullable=True,
        )

    # Wrap the plain strings. Rows already holding a JSON object are left alone,
    # so re-running this (or meeting a row written by a newer client) is a no-op.
    conn = op.get_bind()
    rows = conn.execute(sa.text('SELECT id, name, description FROM data_sources')).fetchall()
    for row_id, name, description in rows:
        updates = {}
        if name and not _is_json_object(name):
            updates['name'] = json.dumps({_LEGACY_LANG: name})
        # '' is the old server_default and means "no description", not a value.
        if description and not _is_json_object(description):
            updates['description'] = json.dumps({_LEGACY_LANG: description})
        elif description == '':
            updates['description'] = None
        if updates:
            assignments = ', '.join(f'{col} = :{col}' for col in updates)
            conn.execute(
                sa.text(f'UPDATE data_sources SET {assignments} WHERE id = :id'),
                {**updates, 'id': row_id},
            )


def downgrade() -> None:
    # Unwrap back to the single legacy language, so the column fits String(255)
    # again. Any other language recorded since the upgrade is dropped.
    conn = op.get_bind()
    rows = conn.execute(sa.text('SELECT id, name, description FROM data_sources')).fetchall()
    for row_id, name, description in rows:
        updates = {}
        for column, raw in (('name', name), ('description', description)):
            if not raw or not _is_json_object(raw):
                continue
            value = json.loads(raw)
            updates[column] = value.get(_LEGACY_LANG) or next(iter(value.values()), '')
        if updates:
            assignments = ', '.join(f'{col} = :{col}' for col in updates)
            conn.execute(
                sa.text(f'UPDATE data_sources SET {assignments} WHERE id = :id'),
                {**updates, 'id': row_id},
            )

    # NOT NULL is about to come back, so the nulls this migration created (and
    # any written since) need a value first.
    conn.execute(sa.text("UPDATE data_sources SET description = '' WHERE description IS NULL"))

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.alter_column('name', existing_type=sa.Text(), type_=sa.String(length=255))
        batch_op.alter_column(
            'description',
            existing_type=sa.Text(),
            type_=sa.Text(),
            server_default='',
            nullable=False,
        )
