"""readme+notes to json, drop readme_history

Revision ID: c5f24c0732da
Revises: be73afd43dcd
Create Date: 2026-07-10 13:43:34.644429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'c5f24c0732da'
down_revision: Union[str, None] = 'be73afd43dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('readme',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_column('readme_history')

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('readme',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('readme',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readme_history', sa.JSON(), nullable=True))
        batch_op.alter_column('readme',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
