"""cohorts

Revision ID: d0f3dc3aefc4
Revises: 808b1ba5efe8
Create Date: 2026-07-08 12:32:21.111179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd0f3dc3aefc4'
down_revision: Union[str, None] = '808b1ba5efe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('criteria_tree', sa.JSON(), nullable=False),
    sa.Column('custom_sql', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('attrition', sa.JSON(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], name=op.f('fk_cohorts_project_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cohorts')
    # ### end Alembic commands ###
