"""schema_presets author provenance

Revision ID: d28c7215fd28
Revises: 669558a7416a
Create Date: 2026-07-14 10:49:28.417408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'd28c7215fd28'
down_revision: Union[str, None] = '669558a7416a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schema_presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by_details', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_schema_presets_created_by_id'), 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schema_presets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_schema_presets_created_by_id'), type_='foreignkey')
        batch_op.drop_column('created_by_details')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
