"""schema presets gain id + entity_id, like every other entity

A preset's `preset_id` plays three roles at once — local primary key, the
user-facing slug shown in the UI and carried in the URL, and (before lineage
existed) its cross-instance identity. Every other entity splits those into
`id` + `entity_id` + `lineage_id`, and the conflation is what forces the
special-casing scattered through the app (`row.uid ?? row.id ?? row.presetId`,
`getattr(entity, "id", None) or entity.preset_id`, a catalog that mints
`custom-<8hex>` instead of a uuid so the user is not shown a 36-character id).

This revision only ADDS the two columns and backfills them; `preset_id` stays
the primary key. Switching the PK is a separate step, deliberately: filling the
columns first means the switch has populated data to move to, and a client that
predates them keeps working meanwhile.

Backfill rule — `entity_id` takes the existing `preset_id`, because that IS the
readable slug users already know (`omop-cdm-5-4`) and it is what the published
repos and their folder names carry. `id` takes it too rather than a fresh uuid:
the rows are already keyed by it everywhere (git working trees, README
attachment owners, git_sync_state), so inventing a new value here would orphan
all of those. New rows get a real uuid from the client.

Revision ID: d5e6f7a8b9c0
Revises: c3d4e5f8a1b2
Create Date: 2026-08-25 20:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'd5e6f7a8b9c0'
down_revision: Union[str, None] = 'c3d4e5f8a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('schema_presets', sa.Column('id', sa.String(length=36), nullable=True))
    op.add_column('schema_presets', sa.Column('entity_id', sa.String(length=255), nullable=True))
    # Backfill both from the current key: it is the slug users know, and the id
    # every other subsystem already points at.
    op.execute(
        "UPDATE schema_presets SET id = preset_id, entity_id = preset_id "
        "WHERE id IS NULL"
    )


def downgrade() -> None:
    op.drop_column('schema_presets', 'entity_id')
    op.drop_column('schema_presets', 'id')
