"""source concept id ranges and entries

Revision ID: d837af51f909
Revises: 06575a567d10
Create Date: 2026-07-08 13:32:10.987933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd837af51f909'
down_revision: Union[str, None] = '06575a567d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_concept_id_entries',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('badge_label', sa.String(length=255), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=255), nullable=False),
    sa.Column('concept_code', sa.String(length=255), nullable=False),
    sa.Column('source_concept_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_concept_id_entries_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_concept_id_entries'))
    )
    op.create_table('source_concept_id_ranges',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('badge_label', sa.String(length=255), nullable=False),
    sa.Column('range_start', sa.BigInteger(), nullable=False),
    sa.Column('range_end', sa.BigInteger(), nullable=False),
    sa.Column('next_id', sa.BigInteger(), nullable=False),
    sa.Column('total_concepts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_concept_id_ranges_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'badge_label', name=op.f('pk_source_concept_id_ranges'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_concept_id_ranges')
    op.drop_table('source_concept_id_entries')
    # ### end Alembic commands ###
