"""organization localized fields tolerant text

Revision ID: d9d134a10a0c
Revises: 473bb2bb176f
Create Date: 2026-07-06 14:16:33.443165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision: str = 'd9d134a10a0c'
down_revision: Union[str, None] = '473bb2bb176f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.JSON(),
               type_=app.models.base.LocalizedText(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.JSON(),
               type_=app.models.base.LocalizedText(),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.JSON(),
               type_=app.models.base.LocalizedText(),
               existing_nullable=True)
        batch_op.alter_column('custom_type',
               existing_type=sa.JSON(),
               type_=app.models.base.LocalizedText(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('custom_type',
               existing_type=app.models.base.LocalizedText(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=app.models.base.LocalizedText(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=app.models.base.LocalizedText(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=app.models.base.LocalizedText(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
