"""schema presets: the primary key becomes `id`

The last step of the identity harmonisation (see
docs/planning/schema-preset-identity-plan.md). `preset_id` stops being the key
and becomes an ordinary column; `id` — the uuid every other entity keys on —
takes over, and `entity_id` holds the readable slug.

**`preset_id` names things outside this table**, which is what makes the move
more than a DDL change:

  - the on-disk git working tree, at data_path/schema-presets/<key>/versioning
  - git_sync_state rows, keyed (scope='schema-presets', entity_id=<key>, branch)
  - README attachments, owned by ("schema-preset", <key>)
  - workspace export exclusions, indexed by <key>

The previous revision (d5e6f7a8b9c0) backfilled `id = entity_id = preset_id`, so
on any database migrated through it the key does not actually change value and
none of the above moves. Rows created *after* that revision carry a real uuid in
`id`, and those DO move — so this revision rewrites git_sync_state in the same
transaction, and a startup task renames the directories (git_service
.rename_schema_preset_repos), which is idempotent and safe to run repeatedly.

Attachments are rewritten here too, for the same reason.

Revision ID: e6f7a8b9c0d1
Revises: d5e6f7a8b9c0
Create Date: 2026-08-25 21:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'e6f7a8b9c0d1'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Safety net: a row that somehow reached here without an id cannot become a
    # primary key value. Fall back to preset_id, which is what the previous
    # revision's backfill would have written.
    op.execute(
        "UPDATE schema_presets SET id = preset_id WHERE id IS NULL OR id = ''"
    )
    op.execute(
        "UPDATE schema_presets SET entity_id = preset_id "
        "WHERE entity_id IS NULL OR entity_id = ''"
    )

    # Re-point the state that names presets by their old key, BEFORE the key
    # moves — a row left behind is a preset whose sync state silently belongs to
    # nothing. A no-op wherever id already equals preset_id.
    op.execute(
        "UPDATE git_sync_state SET entity_id = ("
        "  SELECT p.id FROM schema_presets p WHERE p.preset_id = git_sync_state.entity_id"
        ") "
        "WHERE scope = 'schema-presets' "
        "AND EXISTS ("
        "  SELECT 1 FROM schema_presets p WHERE p.preset_id = git_sync_state.entity_id"
        ")"
    )
    op.execute(
        "UPDATE readme_attachments SET owner_id = ("
        "  SELECT p.id FROM schema_presets p WHERE p.preset_id = readme_attachments.owner_id"
        ") "
        "WHERE owner_type = 'schema-preset' "
        "AND EXISTS ("
        "  SELECT 1 FROM schema_presets p WHERE p.preset_id = readme_attachments.owner_id"
        ")"
    )

    with op.batch_alter_table('schema_presets', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.String(length=36), nullable=False)
        batch_op.drop_constraint('pk_schema_presets', type_='primary')
        batch_op.create_primary_key('pk_schema_presets', ['id'])


def downgrade() -> None:
    with op.batch_alter_table('schema_presets', schema=None) as batch_op:
        batch_op.drop_constraint('pk_schema_presets', type_='primary')
        batch_op.create_primary_key('pk_schema_presets', ['preset_id'])
        batch_op.alter_column('id', existing_type=sa.String(length=36), nullable=True)

    op.execute(
        "UPDATE git_sync_state SET entity_id = ("
        "  SELECT p.preset_id FROM schema_presets p WHERE p.id = git_sync_state.entity_id"
        ") "
        "WHERE scope = 'schema-presets' "
        "AND EXISTS (SELECT 1 FROM schema_presets p WHERE p.id = git_sync_state.entity_id)"
    )
    op.execute(
        "UPDATE readme_attachments SET owner_id = ("
        "  SELECT p.preset_id FROM schema_presets p WHERE p.id = readme_attachments.owner_id"
        ") "
        "WHERE owner_type = 'schema-preset' "
        "AND EXISTS (SELECT 1 FROM schema_presets p WHERE p.id = readme_attachments.owner_id)"
    )
