"""cohort materialization snapshot

Revision ID: e883fbf236cf
Revises: 4866b8aab3b1
Create Date: 2026-07-09 09:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (e.g. LocalizedText).
import app.models.base  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'e883fbf236cf'
down_revision: Union[str, None] = '4866b8aab3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cohorts', sa.Column('materialization', sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column('cohorts', 'materialization')
