"""sql script collections and files

Revision ID: fafc2f7c1533
Revises: 97bcf485d68a
Create Date: 2026-07-07 20:00:48.101987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fafc2f7c1533'
down_revision: Union[str, None] = '97bcf485d68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_script_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('default_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('git_remote_config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sql_script_collections_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sql_script_collections'))
    )
    op.create_table('sql_script_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['sql_script_collections.id'], name=op.f('fk_sql_script_files_collection_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sql_script_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sql_script_files')
    op.drop_table('sql_script_collections')
    # ### end Alembic commands ###
